"""initial_schema

Revision ID: dcbdc1dcc717
Revises: 
Create Date: 2026-04-25 08:53:27.036950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcbdc1dcc717'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = postgresql.ENUM('admin', 'teacher', 'student', name='user_role', create_type=False)
user_status_enum = postgresql.ENUM('active', 'inactive', name='user_status', create_type=False)
group_status_enum = postgresql.ENUM('planned', 'active', 'finished', 'archived', name='group_status', create_type=False)
enrollment_status_enum = postgresql.ENUM('active', 'left', 'finished', name='enrollment_status', create_type=False)
attendance_status_enum = postgresql.ENUM('present', 'absent', 'late', name='attendance_status', create_type=False)
payment_method_enum = postgresql.ENUM('cash', 'card', name='payment_method', create_type=False)
payment_status_enum = postgresql.ENUM('pending', 'paid', name='payment_status', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    user_role_enum.create(bind, checkfirst=True)
    user_status_enum.create(bind, checkfirst=True)
    group_status_enum.create(bind, checkfirst=True)
    enrollment_status_enum.create(bind, checkfirst=True)
    attendance_status_enum.create(bind, checkfirst=True)
    payment_method_enum.create(bind, checkfirst=True)
    payment_status_enum.create(bind, checkfirst=True)

    op.create_table('courses',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_monthly_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=True)
    op.create_table('rooms',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location_note', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('roles', postgresql.ARRAY(user_role_enum), server_default=sa.text("ARRAY['student']::user_role[]"), nullable=False),
    sa.Column('status', user_status_enum, server_default='active', nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('course_fee_histories',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'effective_from', name='uq_course_fee_history_course_effective_from')
    )
    op.create_index(op.f('ix_course_fee_histories_course_id'), 'course_fee_histories', ['course_id'], unique=False)
    op.create_table('groups',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('monthly_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', group_status_enum, server_default='planned', nullable=False),
    sa.Column('schedule_summary', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_course_id'), 'groups', ['course_id'], unique=False)
    op.create_index(op.f('ix_groups_room_id'), 'groups', ['room_id'], unique=False)
    op.create_index(op.f('ix_groups_teacher_id'), 'groups', ['teacher_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_by_teacher_id', sa.UUID(), nullable=True),
    sa.Column('parent_name', sa.String(length=120), nullable=True),
    sa.Column('parent_phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_info', sa.Text(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('telegram_first_name', sa.String(length=255), nullable=True),
    sa.Column('telegram_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_link_token', sa.String(length=255), nullable=True),
    sa.Column('telegram_link_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_last_credentials_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_profiles_telegram_chat_id'), 'student_profiles', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_telegram_link_token'), 'student_profiles', ['telegram_link_token'], unique=True)
    op.create_table('teacher_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('enrollments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.Date(), nullable=False),
    sa.Column('left_at', sa.Date(), nullable=True),
    sa.Column('status', enrollment_status_enum, server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'group_id', name='uq_enrollments_student_group')
    )
    op.create_index(op.f('ix_enrollments_group_id'), 'enrollments', ['group_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('lessons',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('homework', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'lesson_number', name='uq_lessons_group_number')
    )
    op.create_index(op.f('ix_lessons_group_id'), 'lessons', ['group_id'], unique=False)
    op.create_index(op.f('ix_lessons_lesson_date'), 'lessons', ['lesson_date'], unique=False)
    op.create_table('attendance_records',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('para', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('status', attendance_status_enum, server_default='present', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'student_id', 'para', name='uq_attendance_lesson_student_para')
    )
    op.create_index(op.f('ix_attendance_records_enrollment_id'), 'attendance_records', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_lesson_id'), 'attendance_records', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('grades',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_grades_score_percentage'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'student_id', name='uq_grades_lesson_student')
    )
    op.create_index(op.f('ix_grades_enrollment_id'), 'grades', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_grades_lesson_id'), 'grades', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_index(op.f('ix_grades_teacher_id'), 'grades', ['teacher_id'], unique=False)
    op.create_table('payments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('month_for', sa.Date(), nullable=False),
    sa.Column('method', payment_method_enum, nullable=False),
    sa.Column('status', payment_status_enum, nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_enrollment_id'), 'payments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_payments_group_id'), 'payments', ['group_id'], unique=False)
    op.create_index(op.f('ix_payments_month_for'), 'payments', ['month_for'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_month_for'), table_name='payments')
    op.drop_index(op.f('ix_payments_group_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_enrollment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_grades_teacher_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_lesson_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_enrollment_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_lesson_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_enrollment_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_lessons_lesson_date'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_group_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_group_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_table('teacher_profiles')
    op.drop_index(op.f('ix_student_profiles_telegram_link_token'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_telegram_chat_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_groups_teacher_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_room_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_course_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_course_fee_histories_course_id'), table_name='course_fee_histories')
    op.drop_table('course_fee_histories')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_table('courses')

    payment_status_enum.drop(bind, checkfirst=True)
    payment_method_enum.drop(bind, checkfirst=True)
    attendance_status_enum.drop(bind, checkfirst=True)
    enrollment_status_enum.drop(bind, checkfirst=True)
    group_status_enum.drop(bind, checkfirst=True)
    user_status_enum.drop(bind, checkfirst=True)
    user_role_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
